services:
  backend:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: unitube
      JWT_SECRET: unitube-secret-key
    volumes:
      - videos_storage:/storages
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: unitube
    ports:
      - "5432:5432"

volumes:
  videos_storage:
