[agent]
  interval = "10s" # Fréquence de récupération des métriques
  round_interval = true

# 1. SOURCE : Telegraf va lire vos métriques Gin
[[inputs.prometheus]]
  # Grâce à Docker Compose, vous pouvez utiliser directement le nom du conteneur 
  # de votre application Gin (ex: http://mon-app-gin:8089/debug/metrics)
  # Si votre application Gin tourne hors Docker sur votre machine hôte, utilisez : http://host.docker.internal:8089/debug/metrics
  urls = ["http://host.docker.internal:8089/debug/metrics"]

# 2. DESTINATION : Telegraf envoie les données à InfluxDB
[[outputs.influxdb_v2]]
  # Ici aussi, on utilise le nom du conteneur InfluxDB défini dans le docker-compose
  urls = ["http://influxdb:8086"] 
  token = "626nmtf542H3b3z74ZCNypFqdA_ARC1-pISRX3yk_ahfHoHnEiZKAaX9YcoyhVR1jgQ5BehfpWYZqbTwK2EPtQ=="
  organization = "admin"
  bucket = "unitube"